# Generated by Django 3.2.16 on 2022-10-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='disc',
            new_name='desc',
        ),
    ]
